version: '3.4'

services:
  webapp:
    container_name: webapp
    image: webapp:1.0.0
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=blogDb;User Id=sa;Password=Ot!grQJzLp&I;TrustServerCertificate=True;    
    ports:
      - "5000:8080"
    networks:
      - appnet

  mainapp:
    container_name: mainapp
    image: mainapp:1.0.0
    build:
      context: .
      dockerfile: GraphQLSample/Dockerfile
    depends_on:
      - webapp
    environment:
      - Application__Url=http://webapp:8080/api/
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    networks:
      - appnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Ot!grQJzLp&I"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet

networks:
  appnet: